### ISSUE TITLE
D8 issue globaldietarydatabase.org

### ISSUE THREAD

**Issue by eag603** [isovera/Tufts-Friedman#14]
Eric - can you fill in details on what the D8 issue that you resolved with Xia is that also needs to be fixed on the globaldietarydatabase.org site? This ticket is ready for work once those details are filled in.

**Comment by eag603** [comment]
Eric to add estimate once he's dug into the code a bit. Roughly 6-8 hours.

**Comment by ericmaster** [comment]
**Notes:**

- Refactored composer template to use drupal/recommended project and added all contrib modules as dependencies.
- Set proper folder structure under (i.e. document root under ./web)
- Copied over custom code.
- Executed database updates, exported configuration.
- Tested locally and deployed to dev.

**Pending steps:**

- In order to move forward, same as NIL site, we need a bit of help from Marv or someone with access to help us to finish up the deployment

**Comment by eag603** [comment]
Eric to submit ticket to coordinate deploy with Marv.
