### ISSUE TITLE
D8 upgrade? globaldietarydatabase.org	

### ISSUE THREAD

**Issue by eag603** [isovera/Tufts-Friedman#15]
D8 update, from current version to latest version 8. (not upgrading to 9 because not all modules are ready for 9)

**Comment by eag603** [comment]
This will happen in parallel to #14

**Comment by ericmaster** [comment]
**Notes:**

- Updated all contrib modules to latest versions. Core was updated to version 8.9.7.
- Executed database updates and exported config.
- Tested locally and deployed code to dev

**Pending steps:**

- In order to move forward, same as NIL site we need a bit of help from Marv or someone with access to help us to finish up the deployment

**Comment by eag603** [comment]
Eric to submit ticket to coordinate deploy with Marv.
