### ISSUE TITLE
Menu Issue on Food Price Site

### ISSUE THREAD

**Issue by eag603** [isovera/Tufts-Friedman#18]
There is also a menu issue on the food price site (https://www.food-price.org/overview) 
Also fix the issue with left nav not pulling color and icon through: https://foodaidquality.org/focus/data-mining

**Comment by ericmaster** [comment]
I wasn't able to replicate the food-price issue locally, the sidebar menu was missing. Initially I though it was a content issue so re-exported the prod database and re-imported locally but the issue remained. It seemed to be some side-effect of the modules updates that needs to be fixed first.

**Comment by ericmaster** [comment]
- Re the first issue, for the food price site, it has been fixed but it is currently not viewable due to pending it changes that need to coordinate with Marv to deploy to dev and test for review.
- Re the second issue, for the food aid quality site, fixed the colors on the menu by adding manually the colors to the css. Working locally but, getting an error when deployed to dev or test. Attempted to sync the prod database into dev or test and it is triggering some error. Attempted to troubleshoot the issue but it seems we'll need Marv's help as well.

**Comment by eag603** [comment]
with client for review

**Comment by eag603** [comment]
From Xia: The dev site is currently pulling up blank and the menu on the stage site doesnt look like it’s registering the accordion menu

From Eric: weird, dev seemed to be loading fine when we deployed with Marv. I’ll take a look

Eric Aguayo  8 days ago
I think I probably forgot to do a manual update after the deploy, will double check that

**Comment by eag603** [comment]
Asked Xia for specific pages where this is happening.
