### ISSUE TITLE
Images on videos issue on nutrition site

### ISSUE THREAD

**Issue by ericmaster** [isovera/Tufts-Friedman#32]
The images aren’t pulling through on these videos for Dary’s media page: https://nutrition.tufts.edu/media/person/66?type%5B%5D=video&filters=hide-news&field_media_type_tid=292

Specifically these videos: https://nutrition.tufts.edu/video/food-thought-nutrition-policy-summit and https://nutrition.tufts.edu/video/data-informed-nutrition-policy-and-practices

**Comment by ericmaster** [comment]
Updated via e-mail on the reason why images are not being pulled from sources.

**Comment by eag603** [comment]
Email sent to Xia:

I took a deeper look today at the image issue on video content and figured out what is happening. Currently I see 3 pieces of content that are not pulling the images and the main issue is that current solution only parses URLs from youtube and vimeo and in the case of vimeo it uses an old API endpoint which doesn't support private videos:

https://nutrition.tufts.edu/video/how-nutrition-can-help-fight-covid-19
In this case the link that references is https://www.boston25news.com/news/tufts-university-dean-talks-about-how-nutrition-can-help-fight-covid-19/d93c294e-32de-4852-911d-fab2b12c98c0/ which returns an HTML page that contains a video. Since it is not recognized as a youtube or vimeo link, it is skipped. I'd probably recommend to use a generic image or allow content editors to upload a custom image? or both? Let me know how we should proceed in this case.
https://nutrition.tufts.edu/video/data-informed-nutrition-policy-and-practices
URL provided in this case is https://www.atlanticcouncil.org/blogs/geotech-cues/event-recap-data-informed-nutrition-policy-and-initiatives/ which returns an HTML page that contains a youtube video but since the direct video URL wasn't provided, it is not recognized as a youtube link. This could be solved by replacing the link with a youtube link but I'm not sure if that is what is desired in this case, as maybe the page may be linked for additional context?.
https://nutrition.tufts.edu/video/food-thought-nutrition-policy-summit
This is indeed a vimeo link but it corresponds to a private video (which is unlisted and cannot be accessed directly). This could be easily solved if the video is made public or somehow re-published as public. Another option which will take some effort (6 - 8 hours) involves integrating with the new API and updating the parsing function, this is a bit more difficult because it requires to authenticate the API call as it cannot be accessed publicly most likely will require to use a vimeo account for that. Let me know if I should proceed with this integration.

**Comment by eag603** [comment]
In slack Xia told Eric they want to use an image for the video.

"Annie and I discussed the feedback and decided that we should just have a default image that I’ll have Sarah create"

**Comment by eag603** [comment]
Emily to ask Xia about when we can expect the image.

**Comment by eag603** [comment]
[Media_Thumbnails.zip](https://github.com/isovera/Tufts-Friedman/files/6149903/Media_Thumbnails.zip)
use the blank one for the videos. There should  already be one for Podcasts

**Comment by eag603** [comment]
Eric already let Xia know this on dev for her review.
