### ISSUE TITLE
Error when trying to push/pull content across dev/stage/prod on this site: https://nutritioninnovationlab.org/

### ISSUE THREAD

**Issue by eag603** [isovera/Tufts-Friedman#7]
**Problem:** 

An error occurs when trying to push/pull content across dev/stage/prod on this site:
https://nutritioninnovationlab.org/

Xia has described what she and the server admin at Tufts (Marv) have found as the issue, but the client would like us to take a look and advise.

Background from Xia: The current challenge with NIL is that none of the content is migrating across the different sites. So far we've accessed with our system admin guy, Marv, that the NIL is a drupal 8 site built with a tarball, but the new drupal 8 sites are built as composer drupal project. I have a feeling we might have to just rebuilt it with drupal 8 with composer. 

**Tasks**

- [x] Identify questions we have for the client
- [x] Discuss on a client call

**Comment by ericmaster** [comment]
**Questions for the client:**

- Just as a clarification, the issue arises when syncing content (database files) between environments?
- What is the typical workflow? Do we need to sync content upstream? Meaning dev > stage > prod?

**Findings:**

- Triggered a backup from the prod environment for testing purpose. Files backup didn't seem to have an issue but database seemed to have failed as I see the following error in the output log: `mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces`
- Search and checked a past ouput log for the content sync process in jenkins. For instance, https://jenkins.it.tufts.edu/job/drupalpanel-sync-content/3655/console, the database sync triggers an error, apparently because the drush alias @nil-stage.nutrition.tufts.edu.local is not found. It is possible that by setting a drush alias that is compatible with the drush version used globally solves the issue.
- Reviewed the code and it does seem to be using composer but it is using a very old version of composer in which the webroot is shared with the repository root, and drush doesn't seem to be installed for the project.

**Next steps**
- Clarify workflow and make sure to have steps to consistently replicate the issue.
- Update local drush version and ensure existance of corresponding drush aliases. LOE: 3 hours
- Migrate composer to new template. LOE: 12 hours.
